[package]
name = "ahfs_cli"
version = "0.1.0"
authors = ["Emanuel Palm <emanuel.palm@ltu.se>"]
edition = "2018"

[dependencies]
ahfs = { path = "../ahfs" }
ahfs_macro = { path = "../ahfs_macro" }
ahfs_parse = { path = "../ahfs_parse" }
