[package]
name = "arspec_macro"
version = "0.1.0"
authors = ["Emanuel Palm <emanuel.palm@ltu.se>"]
edition = "2018"

[features]
default = ["vt100"]

# If enabled, various VT100 terminal commands, such as for printing in color,
# will be used.
vt100 = []