[package]
name = "ahfs"
version = "0.1.0"
authors = ["Emanuel Palm <emanuel.palm@ltu.se>"]
edition = "2018"

[dependencies]
ahfs_macro = { path = "../ahfs_macro" }
serde = { version = "1.0", features = ["serde_derive"] }
toml = { version = "0.5" }